dotenv: .env
constructor-args:
  contract_name: ${TOKEN_NAME}
  contract_symbol: ${TOKEN_SYMBOL}
  owner_contract: ${OWNER_CONTRACT}
  contract_description: ${CONTRACT_DESCRIPTION}
  contract_registry_id: ${CONTRACT_REGISTRY_ID}
p2p_platform-args:
  allowed_p2p: ${P2P_PLATFORM}
  new_owner: ${NEW_OWNER}
gas_price_increase_coefficient: ${GAS_PRICE_INCREASE_COEFFICIENT}
wallets:
  from_key: ${ACCOUNT_PRIVATE_KEY}
  owner: ${OWNER_CONTRACT}
networks:
  default: development
  development:
    verify: False
  ganache-local:
    verify: False
  bsc-test:
    verify: True
  rinkeby:
    verify: True
  polygon-test:
    verify: True
  mainnet:
    verify: True
  polygon-main:
    verify: True
  kitsoft-ber:
    verify: False
